CREATE DATABASE inlock_games_dbFirst_manha
USE inlock_games_dbFirst_manha

CREATE TABLE Estudio
(
	IdEstudio UNIQUEIDENTIFIER PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
)

CREATE TABLE Jogo
(
	IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
	IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio),
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL
)

CREATE TABLE TiposUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario),
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)
INSERT INTO Estudio
VALUES (NEWID(), 'SENAI'), (NEWID(), 'SESI'), (NEWID(), 'SEBRAE')

INSERT INTO Jogo
VALUES (NEWID(), '0FACC020-AD3D-42DF-ACB0-B41FBF9DFC31', 'PING PONG', 'JOGO LEGAL', '2023-01-01', 500),
		(NEWID(), '0FACC020-AD3D-42DF-ACB0-B41FBF9DFC31', 'JUCAMOM', 'CACA POKEMON', '2022-03-23', 2)

SELECT * FROM Jogo

INSERT INTO TiposUsuario
VALUES (NEWID(),'administrador'), (NEWID(),'comum')

SELECT * FROM TiposUsuario

INSERT INTO Usuario
VALUES(NEWID(),'6453A5DF-AEDC-4CAD-9B03-4E47A8F4C12E', 'adm@adm.com', 'admin'),
		(NEWID(), 'C00CEAAE-76C4-4D0D-976F-A8133B17E95D', 'comum@comum.com', 'comum')

SELECT * FROM Usuario